type Object = { [key: string]: string };

export type Submission = Object & {
  _date: string;
  _id: number;
  _status: any;
  username: string;
};

export const submissions = [
  {
    _date: "2021-06-28T12:03:53.111892+00:00",
    _id: 16273154,
    _status: {
      "baramatzzu@gmail.com": {
        delivered: true,
        dispatched: true,
        processed: true,
      },
    },
    username: "Retz",
    "fri-10pm": "on",
    "fri-11pm": "on",
    "fri-8pm": "on",
    "fri-9pm": "on",
    "mon-10pm": "on",
    "mon-8pm": "on",
    "mon-9pm": "on",
    "sat-10pm": "on",
    "sat-11pm": "on",
    "sat-5pm": "on",
    "sat-6pm": "on",
    "sat-7pm": "on",
    "sat-8pm": "on",
    "sat-9pm": "on",
    "sun-10pm": "on",
    "sun-5pm": "on",
    "sun-6pm": "on",
    "sun-7pm": "on",
    "sun-8pm": "on",
    "sun-9pm": "on",
    "thu-10pm": "on",
    "thu-8pm": "on",
    "thu-9pm": "on",
    "tus-10pm": "on",
    "tus-8pm": "on",
    "tus-9pm": "on",
    "wed-10pm": "on",
    "wed-8pm": "on",
    "wed-9pm": "on",
  },
  {
    _date: "2021-06-28T03:09:42.923872+00:00",
    _id: 16266085,
    _status: {
      "baramatzzu@gmail.com": {
        delivered: true,
        dispatched: true,
        processed: true,
      },
    },
    "fri-10pm": "on",
    "fri-4pm": "on",
    "fri-5pm": "on",
    "fri-6pm": "on",
    "fri-7pm": "on",
    "fri-8pm": "on",
    "fri-9pm": "on",
    "mon-10pm": "on",
    "mon-4pm": "on",
    "mon-5pm": "on",
    "mon-6pm": "on",
    "mon-7pm": "on",
    "mon-8pm": "on",
    "mon-9pm": "on",
    "thu-10pm": "on",
    "thu-4pm": "on",
    "thu-5pm": "on",
    "thu-6pm": "on",
    "thu-7pm": "on",
    "thu-8pm": "on",
    "thu-9pm": "on",
    "tus-10pm": "on",
    "tus-4pm": "on",
    "tus-5pm": "on",
    "tus-6pm": "on",
    "tus-7pm": "on",
    "tus-8pm": "on",
    "tus-9pm": "on",
    username: "Manu2JZ",
    "wed-10pm": "on",
    "wed-4pm": "on",
    "wed-5pm": "on",
    "wed-6pm": "on",
    "wed-7pm": "on",
    "wed-8pm": "on",
    "wed-9pm": "on",
  },
  {
    _date: "2021-06-28T03:07:47.901492+00:00",
    _id: 16266073,
    _status: {
      "baramatzzu@gmail.com": {
        delivered: true,
        dispatched: true,
        processed: true,
      },
    },
    "fri-10pm": "on",
    "fri-11pm": "on",
    "fri-9pm": "on",
    "mon-10pm": "on",
    "mon-11pm": "on",
    "mon-9pm": "on",
    "sat-10pm": "on",
    "sat-11pm": "on",
    "sat-9pm": "on",
    "sun-10pm": "on",
    "sun-11pm": "on",
    "sun-9pm": "on",
    "thu-10pm": "on",
    "thu-11pm": "on",
    "thu-9pm": "on",
    "tus-10pm": "on",
    "tus-11pm": "on",
    "tus-9pm": "on",
    username: "Jarv // Nagini",
    "wed-10pm": "on",
    "wed-11pm": "on",
    "wed-9pm": "on",
  },
  {
    _date: "2021-06-28T03:05:26.841296+00:00",
    _id: 16266040,
    _status: {
      "baramatzzu@gmail.com": {
        delivered: true,
        dispatched: true,
        processed: true,
      },
    },
    "mon-7pm": "on",
    "mon-8pm": "on",
    "sun-6pm": "on",
    "sun-7pm": "on",
    "sun-8pm": "on",
    username: "Pooch",
  },
  {
    _date: "2021-06-28T02:59:27.374135+00:00",
    _id: 16265987,
    _status: {
      "baramatzzu@gmail.com": {
        delivered: true,
        dispatched: true,
        processed: true,
      },
    },
    "fri-10pm": "on",
    "fri-9pm": "on",
    "mon-10pm": "on",
    "mon-9pm": "on",
    "sat-10pm": "on",
    "sat-11pm": "on",
    "sat-4pm": "on",
    "sat-5pm": "on",
    "sat-6pm": "on",
    "sat-7pm": "on",
    "sat-8pm": "on",
    "sat-9pm": "on",
    "sun-10pm": "on",
    "sun-11pm": "on",
    "sun-3pm": "on",
    "sun-4pm": "on",
    "sun-5pm": "on",
    "sun-6pm": "on",
    "sun-7pm": "on",
    "sun-8pm": "on",
    "sun-9pm": "on",
    "thu-10pm": "on",
    "thu-9pm": "on",
    "tus-10pm": "on",
    "tus-9pm": "on",
    username: "Iconik (Gil)",
    "wed-10pm": "on",
    "wed-9pm": "on",
  },
  {
    _date: "2021-06-28T01:06:52.764003+00:00",
    _id: 16264906,
    _status: {
      "baramatzzu@gmail.com": {
        delivered: true,
        dispatched: true,
        processed: true,
      },
    },
    "fri-10pm": "on",
    "fri-11pm": "on",
    "fri-7pm": "on",
    "fri-8pm": "on",
    "fri-9pm": "on",
    "mon-10pm": "on",
    "mon-11pm": "on",
    "mon-7pm": "on",
    "mon-8pm": "on",
    "mon-9pm": "on",
    "sat-10pm": "on",
    "sat-11pm": "on",
    "sat-3pm": "on",
    "sat-4pm": "on",
    "sat-5pm": "on",
    "sat-6pm": "on",
    "sat-7pm": "on",
    "sat-8pm": "on",
    "sat-9pm": "on",
    "sun-10pm": "on",
    "sun-11pm": "on",
    "sun-3pm": "on",
    "sun-4pm": "on",
    "sun-5pm": "on",
    "sun-6pm": "on",
    "sun-7pm": "on",
    "sun-8pm": "on",
    "sun-9pm": "on",
    "thu-10pm": "on",
    "thu-11pm": "on",
    "thu-7pm": "on",
    "thu-8pm": "on",
    "thu-9pm": "on",
    "tus-10pm": "on",
    "tus-11pm": "on",
    "tus-7pm": "on",
    "tus-8pm": "on",
    "tus-9pm": "on",
    username: "reyronald",
    "wed-10pm": "on",
    "wed-11pm": "on",
    "wed-7pm": "on",
    "wed-8pm": "on",
    "wed-9pm": "on",
  },
] as any as Submission[];
